<?php
/**
 * FetchedStoreTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  KwelangaAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kwelanga Online Solutions
 *
 * OpenAPI for Kwelanga Online Solutions
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@kwelangasolutions.co.za
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace KwelangaAPI;

use PHPUnit\Framework\TestCase;

/**
 * FetchedStoreTest Class Doc Comment
 *
 * @category    Class
 * @description FetchedStore
 * @package     KwelangaAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FetchedStoreTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FetchedStore"
     */
    public function testFetchedStore()
    {
    }

    /**
     * Test attribute "deliver_name"
     */
    public function testPropertyDeliverName()
    {
    }

    /**
     * Test attribute "deliver_add1"
     */
    public function testPropertyDeliverAdd1()
    {
    }

    /**
     * Test attribute "deliver_add2"
     */
    public function testPropertyDeliverAdd2()
    {
    }

    /**
     * Test attribute "deliver_add3"
     */
    public function testPropertyDeliverAdd3()
    {
    }

    /**
     * Test attribute "bill_name"
     */
    public function testPropertyBillName()
    {
    }

    /**
     * Test attribute "bill_add1"
     */
    public function testPropertyBillAdd1()
    {
    }

    /**
     * Test attribute "bill_add2"
     */
    public function testPropertyBillAdd2()
    {
    }

    /**
     * Test attribute "bill_add3"
     */
    public function testPropertyBillAdd3()
    {
    }

    /**
     * Test attribute "principal_chain_uid"
     */
    public function testPropertyPrincipalChainUid()
    {
    }

    /**
     * Test attribute "branch_code"
     */
    public function testPropertyBranchCode()
    {
    }

    /**
     * Test attribute "tel_no1"
     */
    public function testPropertyTelNo1()
    {
    }

    /**
     * Test attribute "tel_no2"
     */
    public function testPropertyTelNo2()
    {
    }

    /**
     * Test attribute "email_add1"
     */
    public function testPropertyEmailAdd1()
    {
    }

    /**
     * Test attribute "email_add2"
     */
    public function testPropertyEmailAdd2()
    {
    }

    /**
     * Test attribute "depot_uid"
     */
    public function testPropertyDepotUid()
    {
    }
}
