<?php
/**
 * PrincipalItemTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  KwelangaAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kwelanga Online Solutions
 *
 * OpenAPI for Kwelanga Online Solutions
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@kwelangasolutions.co.za
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace KwelangaAPI;

use PHPUnit\Framework\TestCase;

/**
 * PrincipalItemTest Class Doc Comment
 *
 * @category    Class
 * @description PrincipalItem
 * @package     KwelangaAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PrincipalItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PrincipalItem"
     */
    public function testPrincipalItem()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "physical_add1"
     */
    public function testPropertyPhysicalAdd1()
    {
    }

    /**
     * Test attribute "physical_add2"
     */
    public function testPropertyPhysicalAdd2()
    {
    }

    /**
     * Test attribute "physical_add3"
     */
    public function testPropertyPhysicalAdd3()
    {
    }

    /**
     * Test attribute "physical_add4"
     */
    public function testPropertyPhysicalAdd4()
    {
    }

    /**
     * Test attribute "postal_add1"
     */
    public function testPropertyPostalAdd1()
    {
    }

    /**
     * Test attribute "postal_add2"
     */
    public function testPropertyPostalAdd2()
    {
    }

    /**
     * Test attribute "postal_add3"
     */
    public function testPropertyPostalAdd3()
    {
    }

    /**
     * Test attribute "postal_add4"
     */
    public function testPropertyPostalAdd4()
    {
    }

    /**
     * Test attribute "office_tel"
     */
    public function testPropertyOfficeTel()
    {
    }

    /**
     * Test attribute "email_add"
     */
    public function testPropertyEmailAdd()
    {
    }
}
