<?php
/**
 * ProductDetailedItemTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  KwelangaAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kwelanga Online Solutions
 *
 * OpenAPI for Kwelanga Online Solutions
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@kwelangasolutions.co.za
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace KwelangaAPI;

use PHPUnit\Framework\TestCase;

/**
 * ProductDetailedItemTest Class Doc Comment
 *
 * @category    Class
 * @description ProductDetailedItem
 * @package     KwelangaAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductDetailedItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductDetailedItem"
     */
    public function testProductDetailedItem()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "alt_code"
     */
    public function testPropertyAltCode()
    {
    }

    /**
     * Test attribute "ean_code"
     */
    public function testPropertyEanCode()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "short_desc"
     */
    public function testPropertyShortDesc()
    {
    }

    /**
     * Test attribute "long_desc"
     */
    public function testPropertyLongDesc()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "items_per_case"
     */
    public function testPropertyItemsPerCase()
    {
    }

    /**
     * Test attribute "web_enabled"
     */
    public function testPropertyWebEnabled()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "image_uri"
     */
    public function testPropertyImageUri()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "pricing"
     */
    public function testPropertyPricing()
    {
    }
}
