<?php
/**
 * ProductDetailedItemPricingTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  KwelangaAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kwelanga Online Solutions
 *
 * OpenAPI for Kwelanga Online Solutions
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@kwelangasolutions.co.za
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace KwelangaAPI;

use PHPUnit\Framework\TestCase;

/**
 * ProductDetailedItemPricingTest Class Doc Comment
 *
 * @category    Class
 * @description ProductDetailedItemPricing
 * @package     KwelangaAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductDetailedItemPricingTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductDetailedItemPricing"
     */
    public function testProductDetailedItemPricing()
    {
    }

    /**
     * Test attribute "inclusive"
     */
    public function testPropertyInclusive()
    {
    }

    /**
     * Test attribute "vat_rate"
     */
    public function testPropertyVatRate()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }
}
