<?php
/**
 * DefaultApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kwelanga Online Solutions
 *
 * OpenAPI for Kwelanga Online Solutions
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@kwelangasolutions.co.za
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteOrderId
     *
     * Delete Order Item.
     *
     */
    public function testDeleteOrderId()
    {
    }

    /**
     * Test case for deletePrincipalsId
     *
     * Delete Principal Item.
     *
     */
    public function testDeletePrincipalsId()
    {
    }

    /**
     * Test case for deleteProductsId
     *
     * Delete Product Item.
     *
     */
    public function testDeleteProductsId()
    {
    }

    /**
     * Test case for deleteStoresId
     *
     * Delete Store Item.
     *
     */
    public function testDeleteStoresId()
    {
    }

    /**
     * Test case for getCustomerProfile
     *
     * Get Customer/Store Profile.
     *
     */
    public function testGetCustomerProfile()
    {
    }

    /**
     * Test case for getOrder
     *
     * Search/List Orders.
     *
     */
    public function testGetOrder()
    {
    }

    /**
     * Test case for getOrderId
     *
     * Fetch Order Item.
     *
     */
    public function testGetOrderId()
    {
    }

    /**
     * Test case for getPing
     *
     * Your GET endpoint.
     *
     */
    public function testGetPing()
    {
    }

    /**
     * Test case for getPrincipals
     *
     * Search/List Principals.
     *
     */
    public function testGetPrincipals()
    {
    }

    /**
     * Test case for getPrincipalsId
     *
     * Fetch Principal Item.
     *
     */
    public function testGetPrincipalsId()
    {
    }

    /**
     * Test case for getProducts
     *
     * Create New Product.
     *
     */
    public function testGetProducts()
    {
    }

    /**
     * Test case for getProductsId
     *
     * Fetch Order Item.
     *
     */
    public function testGetProductsId()
    {
    }

    /**
     * Test case for getStores
     *
     * Search/List Stores.
     *
     */
    public function testGetStores()
    {
    }

    /**
     * Test case for getStoresId
     *
     * Fetch Store Item.
     *
     */
    public function testGetStoresId()
    {
    }

    /**
     * Test case for getSupport
     *
     * Your GET endpoint.
     *
     */
    public function testGetSupport()
    {
    }

    /**
     * Test case for getTestnew
     *
     * Your GET endpoint.
     *
     */
    public function testGetTestnew()
    {
    }

    /**
     * Test case for getUser
     *
     * Your GET endpoint.
     *
     */
    public function testGetUser()
    {
    }

    /**
     * Test case for getUserSettings
     *
     * Fetch User Settings.
     *
     */
    public function testGetUserSettings()
    {
    }

    /**
     * Test case for postCustomerLogin
     *
     * .
     *
     */
    public function testPostCustomerLogin()
    {
    }

    /**
     * Test case for postCustomerProfile
     *
     * Create Customer/Store Profile.
     *
     */
    public function testPostCustomerProfile()
    {
    }

    /**
     * Test case for postOrder
     *
     * Create New Order.
     *
     */
    public function testPostOrder()
    {
    }

    /**
     * Test case for postPrincipals
     *
     * Create New Principal.
     *
     */
    public function testPostPrincipals()
    {
    }

    /**
     * Test case for postProducts
     *
     * Create New Product.
     *
     */
    public function testPostProducts()
    {
    }

    /**
     * Test case for postStores
     *
     * Create New Store.
     *
     */
    public function testPostStores()
    {
    }

    /**
     * Test case for putCustomerProfile
     *
     * Update Customer/Store Profile.
     *
     */
    public function testPutCustomerProfile()
    {
    }

    /**
     * Test case for putOrderId
     *
     * Update Order Item.
     *
     */
    public function testPutOrderId()
    {
    }

    /**
     * Test case for putPrincipalsId
     *
     * Update Principal Item.
     *
     */
    public function testPutPrincipalsId()
    {
    }

    /**
     * Test case for putProductsId
     *
     * Update Product Item.
     *
     */
    public function testPutProductsId()
    {
    }

    /**
     * Test case for putStoresId
     *
     * Update Store Item.
     *
     */
    public function testPutStoresId()
    {
    }

    /**
     * Test case for putUserSettings
     *
     * Update User Settings.
     *
     */
    public function testPutUserSettings()
    {
    }
}
